### DISCUSSION TITLE
Is it valid to call `@plugin "flyonui"` twice for overriding options?

### DISCUSSION THREAD

**Discussion by razonyang** [themeselection/flyonui#102] [Q&A]
Hi, I got a package that hard coded the following style.

```css
@import "tailwindcss";

@plugin "flyonui";
@import "flyonui/variants.css";

@plugin "@iconify/tailwind4";

@source "../";
```

Now, I'd like to allow users to change some options of FlyonUI, for example.

```css
@plugin "flyonui" {
  themes: all;
}
```

Since the users cannot edit that style file, is it valid to invoke the `@plugin` directive twice? Is there any workaground? Thanks.

**Comment by OmkarOza** [comment]
Hi @razonyang,

Thank you for reaching out.

We reviewed your question but couldn’t determine which specific package you’re referring to. Could you please provide more details or context? This will help us assist you more effectively.

Regarding customizing options in FlyonUI, such as enabling all themes, you can do it like this:

```css
@import "tailwindcss";

@plugin "flyonui" {
  themes: all;
}
@import "flyonui/variants.css";

@plugin "@iconify/tailwind4";

@source "../";
```

You might also find the following [documentation](https://flyonui.com/docs/customization/themes/) helpful for more on theme customization.

Best regards,
