### ISSUE TITLE
bug: border left in input with button overlaps border of input

### ISSUE THREAD

**Issue by michaelcozzolino** [themeselection/flyonui#70]
### What version of FlyonUI are you using?

1.3

### Which browsers are you seeing the problem on?

All browsers, Chrome

### Reproduction URL

https://flyonui.com/docs/forms/input/

### Describe your issue

![Image](https://github.com/user-attachments/assets/94c521a1-6905-45a7-8158-bdc4c897f1c2)
in the first element the borders are overlapping, while in the second they are not. they should not overlap i suppose.

**Comment by PruthviPraj00** [comment]
Hello @michaelcozzolino,

In the join component, the following style is applied:  

```css
.join-item {
  &:where(:not(:first-child)) {
    margin-inline-start: calc(var(--border, 1px) * -1);
    margin-block-start: 0;
  }
}
```

In the first example, the button is the second component, causing its border to overlap with the input's border.  

In the second example, the input is the second component, so its border overlaps the button's border.  

Since both components have different border colors, this overlap becomes visually noticeable.

I hope this answers your question.
